version: '3.8'

services:
  mysql:
    build:
      context: ./dockerfiles/mysql
      dockerfile: Dockerfile
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    build:
      context: ./dockerfiles/mongodb
      dockerfile: Dockerfile
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    build:
      context: ./dockerfiles/neo4j
      dockerfile: Dockerfile
    container_name: neo4j_container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  postgres:
    build:
      context: ./dockerfiles/postgres
      dockerfile: Dockerfile
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:
  postgres_data:
